spring:
  datasource:
    url: jdbc:mysql://139.224.134.124:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ulmQX+gUBdC+kA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 10
      max-wait: 10000
      validation-query: SELECT 'x'
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 0
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat
      WebStatFilter.exclusions: /druid/*
      StatViewServlet:
        loginUsername: xxx
        loginPassword: xxx
  redis:
    password: ulmQX+gUBdC+kA==
    host: 139.224.134.124
#  kafka:
#    bootstrap-servers: 192.168.81.66:9092,192.168.81.67:9092,192.168.81.68:9092
#    producer:
#      retries: 3
#      acks: 1
#    consumer:
#      group-id: order
#      auto-offset-reset: earliest
#      auto-commit-interval: 100
#      max-poll-records: 5
mybatis:
    mapper-locations: com.zhangrui.repository.mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /zhangrui-api
security:
  user:
